# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvgl-builder.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1780, 1165)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.GUIEditorTab = QtWidgets.QWidget()
        self.GUIEditorTab.setObjectName("GUIEditorTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GUIEditorTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LVGLSimWindow = LVGLSimulator(self.GUIEditorTab)
        self.LVGLSimWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LVGLSimWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LVGLSimWindow.setObjectName("LVGLSimWindow")
        self.gridLayout_2.addWidget(self.LVGLSimWindow, 0, 0, 1, 1)
        self.tabWidget.addTab(self.GUIEditorTab, "")
        self.StyleEditorTab = QtWidgets.QWidget()
        self.StyleEditorTab.setObjectName("StyleEditorTab")
        self.label = QtWidgets.QLabel(self.StyleEditorTab)
        self.label.setGeometry(QtCore.QRect(380, 400, 231, 81))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.StyleEditorTab, "")
        self.AssetTab = QtWidgets.QWidget()
        self.AssetTab.setObjectName("AssetTab")
        self.label_2 = QtWidgets.QLabel(self.AssetTab)
        self.label_2.setGeometry(QtCore.QRect(390, 410, 231, 81))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.AssetTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1780, 39))
        self.menubar.setObjectName("menubar")
        self.menuLittlevGL_Builder = QtWidgets.QMenu(self.menubar)
        self.menuLittlevGL_Builder.setObjectName("menuLittlevGL_Builder")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.ObjecInspector = QtWidgets.QDockWidget(MainWindow)
        self.ObjecInspector.setBaseSize(QtCore.QSize(330, 300))
        self.ObjecInspector.setObjectName("ObjecInspector")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.object_tree = LVGLTreeView(self.dockWidgetContents)
        self.object_tree.setObjectName("object_tree")
        self.gridLayout_3.addWidget(self.object_tree, 0, 0, 1, 1)
        self.ObjecInspector.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ObjecInspector)
        self.PropertyEditor = QtWidgets.QDockWidget(MainWindow)
        self.PropertyEditor.setBaseSize(QtCore.QSize(330, 300))
        self.PropertyEditor.setObjectName("PropertyEditor")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.property_tree = QtWidgets.QTreeWidget(self.dockWidgetContents_3)
        self.property_tree.setMinimumSize(QtCore.QSize(400, 0))
        self.property_tree.setObjectName("property_tree")
        self.gridLayout_4.addWidget(self.property_tree, 0, 0, 1, 1)
        self.PropertyEditor.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.PropertyEditor)
        self.WidgeBox = QtWidgets.QDockWidget(MainWindow)
        self.WidgeBox.setBaseSize(QtCore.QSize(330, 0))
        self.WidgeBox.setObjectName("WidgeBox")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents_2)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 292, 921))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_7.addWidget(self.listWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.WidgeBox.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.WidgeBox)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionWidget_Box = QtWidgets.QAction(MainWindow)
        self.actionWidget_Box.setCheckable(True)
        self.actionWidget_Box.setObjectName("actionWidget_Box")
        self.actionObject_Inspector = QtWidgets.QAction(MainWindow)
        self.actionObject_Inspector.setCheckable(True)
        self.actionObject_Inspector.setObjectName("actionObject_Inspector")
        self.actionProperty_Editor = QtWidgets.QAction(MainWindow)
        self.actionProperty_Editor.setCheckable(True)
        self.actionProperty_Editor.setObjectName("actionProperty_Editor")
        self.menuLittlevGL_Builder.addAction(self.actionNew)
        self.menuLittlevGL_Builder.addAction(self.actionOpen)
        self.menuView.addSeparator()
        self.menubar.addAction(self.menuLittlevGL_Builder.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LittlevGL GUI Builder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GUIEditorTab), _translate("MainWindow", "GUI Editor"))
        self.label.setText(_translate("MainWindow", "Coming Soon :)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StyleEditorTab), _translate("MainWindow", "Style Editor"))
        self.label_2.setText(_translate("MainWindow", "Coming Soon :)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AssetTab), _translate("MainWindow", "Asset Manager"))
        self.menuLittlevGL_Builder.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.ObjecInspector.setWindowTitle(_translate("MainWindow", "Object Inspector"))
        self.object_tree.headerItem().setText(0, _translate("MainWindow", "Object"))
        self.object_tree.headerItem().setText(1, _translate("MainWindow", "Class"))
        self.PropertyEditor.setWindowTitle(_translate("MainWindow", "Property Editor"))
        self.property_tree.headerItem().setText(0, _translate("MainWindow", "Property"))
        self.property_tree.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.WidgeBox.setWindowTitle(_translate("MainWindow", "Widget Box"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Filter"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionWidget_Box.setText(_translate("MainWindow", "Widget Box"))
        self.actionObject_Inspector.setText(_translate("MainWindow", "Object Inspector"))
        self.actionProperty_Editor.setText(_translate("MainWindow", "Property Editor"))
from LVGLSimulator import LVGLSimulator
from LVGLTreeViewItem import LVGLTreeView
